from typing import TypedDict, Optional

# Type definition of allowed parameters for account.add
# Allowed attributes as documented here: https://api.mailbox.org/v1/doc/methods/index.html#account-add
class AccountAddOptions(TypedDict, total=False):
    tarifflimits: Optional[dict]
    memo: Optional[str]
    contact_mail: Optional[str]
    contact_phone: Optional[str]
    contact_fax: Optional[str]
    contact_mobile: Optional[str]
    company: Optional[str]
    ustid: Optional[str]
    address_main_salutation: Optional[str]
    address_main_first_name: Optional[str]
    address_main_last_name: Optional[str]
    address_main_street: Optional[str]
    address_main_zipcode: Optional[str]
    address_main_town: Optional[str]
    address_main_country: Optional[str]
    address_payment_same_as_main: Optional[bool]
    address_payment_first_name: Optional[str]
    address_payment_last_name: Optional[str]
    address_payment_street: Optional[str]
    address_payment_zipcode: Optional[str]
    address_payment_town: Optional[str]
    address_payment_country: Optional[str]
    max_mailinglist: Optional[int]
    language: Optional[str]

# Type definition of allowed parameters for account.set
# Allowed attributes as documented here: https://api.mailbox.org/v1/doc/methods/index.html#account-set
class AccountSetOptions(TypedDict, total=False):
    password: Optional[str]
    telephone_password: Optional[str]
    plan: Optional[str]
    memo: Optional[str]
    contact_mail: Optional[str]
    contact_mail_payment: Optional[str]
    contact_phone: Optional[str]
    contact_fax: Optional[str]
    contact_mobile: Optional[str]
    address_main_first_name: Optional[str]
    address_main_last_name: Optional[str]
    address_main_street: Optional[str]
    address_main_zipcode: Optional[str]
    address_main_town: Optional[str]
    address_main_country: Optional[str]
    address_payment_same_as_main: Optional[bool]
    address_payment_first_name: Optional[str]
    address_payment_last_name: Optional[str]
    address_payment_street: Optional[str]
    address_payment_zipcode: Optional[str]
    address_payment_town: Optional[str]
    address_payment_country: Optional[str]
    company: Optional[str]
    bank_iban: Optional[str]
    bank_bic: Optional[str]
    bank_account_owner: Optional[str]
    payment_type: Optional[str]
    ustid: Optional[str]
    av_contract_accept_name: Optional[str]
    max_mailinglist: Optional[int]
    tarifflimits: Optional[dict]
    salutation: Optional[str]
    mail_forwarding: Optional[str]
    av_contract_professional_secrecy: Optional[bool]
    language: Optional[str]

# Type definition of allowed parameters for mail.add
# Allowed attributes as documented here: https://api.mailbox.org/v1/doc/methods/index.html#account-add
class MailAddOptions(TypedDict, total=False):
    password_hash: Optional[str]
    require_reset_password: Optional[bool]
    additional_mail_quota: Optional[str]
    additional_cloud_quota: Optional[str]
    memo: Optional[str]
    allow_nets: Optional[str]
    catchall: Optional[bool]
    create_own_context: Optional[bool]
    title: Optional[str]
    birthday: Optional[str]
    position: Optional[str]
    department: Optional[str]
    company: Optional[str]
    street: Optional[str]
    postal_code: Optional[str]
    city: Optional[str]
    phone: Optional[str]
    fax: Optional[str]
    cell_phone: Optional[str]
    recover: Optional[bool]
    skip_welcome_mail: Optional[bool]
    uid_extern: Optional[str]
    language: Optional[str]
    evac_force_activation: Optional[bool]

# Type definition of allowed parameters for mail.set
# Allowed attributes as documented here: https://api.mailbox.org/v1/doc/methods/index.html#mail-set
class MailSetOptions(TypedDict, total=False):
    password: Optional[str]
    password_hash: Optional[str]
    same_password_allowed: Optional[bool]
    require_reset_password: Optional[bool]
    plan: Optional[str]
    additional_mail_quota: Optional[str]
    additional_cloud_quota: Optional[str]
    first_name: Optional[str]
    last_name: Optional[str]
    inboxsave: Optional[bool]
    forwards: Optional[list[str]]
    aliases: Optional[list[str]]
    alternate_mail: Optional[str]
    memo: Optional[str]
    allow_nets: Optional[str]
    active: Optional[bool]
    title: Optional[str]
    birthday: Optional[str]
    position: Optional[str]
    department: Optional[str]
    company: Optional[str]
    street: Optional[str]
    postal_code: Optional[str]
    city: Optional[str]
    phone: Optional[str]
    fax: Optional[str]
    cell_phone: Optional[str]
    uid_extern: Optional[str]
    language: Optional[str]
    deletion_date: Optional[str]

